/*
 * This source file was generated by the Gradle 'init' task
 */
package aop;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.EnableAspectJAutoProxy;

@SpringBootApplication(scanBasePackages = "aop")
@EnableAspectJAutoProxy //detects where aspectJ annotation will be used
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
