/*
 * This source file was generated by the Gradle 'init' task
 */
package springboot

import org.apache.catalina.core.ApplicationContext
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.context.support.ClassPathXmlApplicationContext
import springboot.bean.UserConfig

@SpringBootApplication
class App {

    static void main(String[] args) {
        SpringApplication.run(App, args)
        ApplicationContext context = new ClassPathXmlApplicationContext("applicationContext.xml")
        UserConfig config = (UserConfig) context.getBean(name: "userConfigBean")
    }
}
